  const defaultSkinId = "classic-suit";
  const defaultTrailId = "trail-classic-flame";
  const defaultSuitSkinPalette = Object.freeze({
    swatch: "#f4f2ea",
    torso: "#f4f2ea",
    limb: "#d9dee8",
    arm: "#f8f5ec",
    helmet: "#ffffff",
    panel: "#cfd7e7",
    accent: "#64e3ff"
  });
  const skinCatalog = [
    {
      id: defaultSkinId,
      name: "Classic Suit",
      category: "skins",
      kind: "suit",
      plainColor: "White",
      description: "The standard Clusternauts EVA suit.",
      priceLabel: "Included",
      priceId: "",
      productId: "",
      colors: defaultSuitSkinPalette
    },
    {
      id: defaultTrailId,
      name: "Classic Flame",
      category: "skins",
      kind: "trail",
      plainColor: "Flame",
      description: "The standard short jet flame boost trail.",
      priceLabel: "Included",
      priceId: "",
      productId: "",
      colors: { swatch: "#ff9b34", accent: "#ffe56f" }
    },
    // build:render:start
    {
      id: "suit-mars-red",
      name: "Mars Red",
      category: "skins",
      kind: "suit",
      plainColor: "Red",
      description: "A bold red recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqIDHmsD7gK0nLGi5G02yw",
      productId: "prod_UpVIhwLtcrbcLX",
      colors: { swatch: "#e5484d", torso: "#d9363e", limb: "#b5242e", arm: "#f06f74", helmet: "#fff3f3", panel: "#ffb7bd", accent: "#ffd166" }
    },
    {
      id: "suit-nebula-blue",
      name: "Nebula Blue",
      category: "skins",
      kind: "suit",
      plainColor: "Blue",
      description: "A deep blue recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqIvHmsD7gK0nLHwkuHLye",
      productId: "prod_UpVJImzN2j9OCW",
      colors: { swatch: "#3578ff", torso: "#2d6cdf", limb: "#1c4fb2", arm: "#75a6ff", helmet: "#eef5ff", panel: "#9fc3ff", accent: "#58e2ff" }
    },
    {
      id: "suit-solar-yellow",
      name: "Solar Yellow",
      category: "skins",
      kind: "suit",
      plainColor: "Yellow",
      description: "A bright yellow recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqJXHmsD7gK0nLmmluSuPx",
      productId: "prod_UpVK0wvBk7hNwi",
      colors: { swatch: "#ffd84d", torso: "#f2c933", limb: "#cf9f19", arm: "#ffe783", helmet: "#fff9df", panel: "#ffe29a", accent: "#ff8f3d" }
    },
    {
      id: "suit-toxic-green",
      name: "Toxic Green",
      category: "skins",
      kind: "suit",
      plainColor: "Green",
      description: "A vivid green recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqK4HmsD7gK0nLlzk0qOD0",
      productId: "prod_UpVKSFCiD7glhv",
      colors: { swatch: "#5cf06d", torso: "#38c957", limb: "#269945", arm: "#8cff9b", helmet: "#effff1", panel: "#9dffad", accent: "#dffcff" }
    },
    {
      id: "suit-void-purple",
      name: "Void Purple",
      category: "skins",
      kind: "suit",
      plainColor: "Purple",
      description: "A saturated purple recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqKcHmsD7gK0nLzoihm1RW",
      productId: "prod_UpVLEO9dUJB4g5",
      colors: { swatch: "#a985ff", torso: "#8657e8", limb: "#6840bf", arm: "#bda0ff", helmet: "#f6f0ff", panel: "#c8b4ff", accent: "#ff73ad" }
    },
    {
      id: "suit-hazard-orange",
      name: "Hazard Orange",
      category: "skins",
      kind: "suit",
      plainColor: "Orange",
      description: "A high-visibility orange recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqKxHmsD7gK0nLcWWIWE2C",
      productId: "prod_UpVLumOKnxlkQK",
      colors: { swatch: "#ff8a34", torso: "#ef7428", limb: "#b9541f", arm: "#ffad66", helmet: "#fff2e8", panel: "#ffc18c", accent: "#ffd166" }
    },
    {
      id: "suit-cosmic-pink",
      name: "Cosmic Pink",
      category: "skins",
      kind: "suit",
      plainColor: "Pink",
      description: "A luminous pink recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqMUHmsD7gK0nLGLEuNwVH",
      productId: "prod_UpVNQXqJJxgw40",
      colors: { swatch: "#ff73ad", torso: "#ee5d9e", limb: "#bd3f7b", arm: "#ffa4ca", helmet: "#fff0f7", panel: "#ffbfd9", accent: "#64e3ff" }
    },
    {
      id: "suit-deep-space-black",
      name: "Deep Space Black",
      category: "skins",
      kind: "suit",
      plainColor: "Black",
      description: "A low-profile black recolour for your space suit.",
      priceLabel: "\u00a32",
      priceId: "price_1TpqN2HmsD7gK0nL57YnS6g5",
      productId: "prod_UpVNBsf8zX01pX",
      colors: { swatch: "#05070c", torso: "#111827", limb: "#273244", arm: "#384359", helmet: "#e8edf8", panel: "#636f84", accent: "#dffcff" }
    },
    {
      id: "costume-medieval-knight",
      name: "Medieval Knight",
      category: "skins",
      kind: "costume",
      model: "medieval-knight",
      plainColor: "Steel",
      description: "A full medieval knight costume with plate armour, visor helm, and tabard.",
      priceLabel: "\u00a35",
      priceId: "price_1TpwkmHmsD7gK0nLwrApMz0J",
      productId: "prod_UpbykcgnkcJwSM",
      colors: { swatch: "#b7c0cc", torso: "#9aa6b6", limb: "#7d8998", arm: "#c9d1dc", helmet: "#d9dee8", panel: "#6b3f2a", accent: "#d94b4b" }
    },
    {
      id: "costume-pirate",
      name: "Pirate",
      category: "skins",
      kind: "costume",
      model: "pirate",
      plainColor: "Black",
      description: "A swashbuckling pirate costume with tricorn hat, sash, and sea-worn coat.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvXUHmsD7gK0nLCx9yxOSX",
      productId: "prod_UpaivbIkPP1Coh",
      colors: { swatch: "#23202a", torso: "#332842", limb: "#171827", arm: "#f2eadb", helmet: "#201726", panel: "#7b3e24", accent: "#d94b4b" }
    },
    {
      id: "costume-wizard",
      name: "Wizard",
      category: "skins",
      kind: "costume",
      model: "wizard",
      plainColor: "Indigo",
      description: "A starry wizard robe and pointed hat for arcane drifting.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvbWHmsD7gK0nLCRORBFNW",
      productId: "prod_Upanwyix8W2oUV",
      colors: { swatch: "#5b4bc4", torso: "#3d318f", limb: "#27205f", arm: "#d8d0ff", helmet: "#594ad0", panel: "#f0d275", accent: "#ffd166" }
    },
    {
      id: "costume-cowboy",
      name: "Cowboy",
      category: "skins",
      kind: "costume",
      model: "cowboy",
      plainColor: "Brown",
      description: "A frontier outfit with hat, vest, boots, and bandana.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvdQHmsD7gK0nLARH5jiK6",
      productId: "prod_Upaps0nejQRQas",
      colors: { swatch: "#a16335", torso: "#8b4e29", limb: "#4f3626", arm: "#f2d0a2", helmet: "#b6783d", panel: "#2f5c91", accent: "#d94b4b" }
    },
    {
      id: "costume-ninja",
      name: "Ninja",
      category: "skins",
      kind: "costume",
      model: "ninja",
      plainColor: "Black",
      description: "A stealth ninja costume with hood, mask, and dark wraps.",
      priceLabel: "\u00a35",
      priceId: "price_1Tpvf3HmsD7gK0nLRIQah37C",
      productId: "prod_UpaqYppQTFsNos",
      colors: { swatch: "#07090f", torso: "#111827", limb: "#05070c", arm: "#1f2937", helmet: "#0b0f18", panel: "#3b4458", accent: "#66e0b8" }
    },
    {
      id: "costume-viking",
      name: "Viking",
      category: "skins",
      kind: "costume",
      model: "viking",
      plainColor: "Fur",
      description: "A fur-lined viking outfit with horned helm and rugged tunic.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvgIHmsD7gK0nLKKPGvBuz",
      productId: "prod_UpascR0hqgOq2d",
      colors: { swatch: "#8a5b3d", torso: "#6f442d", limb: "#4b2d20", arm: "#d1c1ad", helmet: "#c6ccd4", panel: "#f2eadb", accent: "#58e2ff" }
    },
    {
      id: "costume-samurai",
      name: "Samurai",
      category: "skins",
      kind: "costume",
      model: "samurai",
      plainColor: "Crimson",
      description: "Layered samurai armour with crest helm and plated skirt.",
      priceLabel: "\u00a35",
      priceId: "price_1TpviGHmsD7gK0nLD7WXSVoy",
      productId: "prod_UpaufRtxQHUhbF",
      colors: { swatch: "#9b2634", torso: "#7f1d2d", limb: "#2f1f24", arm: "#b9a58c", helmet: "#2b2630", panel: "#d0a64f", accent: "#ff6262" }
    },
    {
      id: "costume-diver",
      name: "Diver",
      category: "skins",
      kind: "costume",
      model: "diver",
      plainColor: "Brass",
      description: "An old deep-sea diving suit with brass helmet and porthole visor.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvjzHmsD7gK0nLzdBIdZa0",
      productId: "prod_UpavxAM0KGm8C6",
      colors: { swatch: "#b98135", torso: "#7c4f2b", limb: "#4b3628", arm: "#b8894d", helmet: "#d0a64f", panel: "#2d6cdf", accent: "#58e2ff" }
    },
    {
      id: "costume-firefighter",
      name: "Firefighter",
      category: "skins",
      kind: "costume",
      model: "firefighter",
      plainColor: "Red",
      description: "A firefighter uniform with helmet, coat, and reflective stripes.",
      priceLabel: "\u00a35",
      priceId: "price_1Tpvl9HmsD7gK0nLzfe6Jk7R",
      productId: "prod_UpaxCnSYRhVofB",
      colors: { swatch: "#d9363e", torso: "#9f1f2e", limb: "#5d1f24", arm: "#ef6b6f", helmet: "#e5484d", panel: "#222936", accent: "#ffd166" }
    },
    {
      id: "costume-doctor",
      name: "Doctor",
      category: "skins",
      kind: "costume",
      model: "doctor",
      plainColor: "White",
      description: "A doctor costume with white coat, scrubs, and medical badge.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvmnHmsD7gK0nLwOaEMmif",
      productId: "prod_UpaytIlrxZMx5B",
      colors: { swatch: "#f8fbff", torso: "#f1f5f9", limb: "#d8dee8", arm: "#f8fbff", helmet: "#dffcff", panel: "#58e2ff", accent: "#ef6262" }
    },
    {
      id: "costume-clown",
      name: "Clown",
      category: "skins",
      kind: "costume",
      model: "clown",
      plainColor: "Rainbow",
      description: "A bright clown costume with oversized buttons, ruffle, and red nose.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvnOHmsD7gK0nLxWFcHxrG",
      productId: "prod_Upaz3a0k9cMuZP",
      colors: { swatch: "#ff73ad", torso: "#f8fbff", limb: "#3578ff", arm: "#ffd84d", helmet: "#ffffff", panel: "#a985ff", accent: "#ef6262" }
    },
    {
      id: "costume-santa",
      name: "Santa",
      category: "skins",
      kind: "costume",
      model: "santa",
      plainColor: "Red",
      description: "A festive Santa costume available during December.",
      priceLabel: "\u00a35",
      priceId: "price_1TpvzJHmsD7gK0nLv9RyyLZp",
      productId: "prod_UpbBcT4VxpYQk0",
      availability: { type: "month", month: 12, label: "Available in December" },
      colors: { swatch: "#d9363e", torso: "#c52835", limb: "#6b1d22", arm: "#f8fbff", helmet: "#d9363e", panel: "#111827", accent: "#f8fbff" }
    },
    {
      id: "costume-skeleton",
      name: "Skeleton",
      category: "skins",
      kind: "costume",
      model: "skeleton",
      plainColor: "Bone",
      description: "A spooky skeleton costume available on 31/10 and 01/11.",
      priceLabel: "\u00a35",
      priceId: "price_1Tpvq0HmsD7gK0nLynQlHhT8",
      productId: "prod_Upb2FLniFOUZlU",
      availability: { type: "dates", dates: ["10-31", "11-01"], label: "Available on 31/10 and 01/11" },
      colors: { swatch: "#f1ead8", torso: "#111827", limb: "#0b0f18", arm: "#e8dcc4", helmet: "#efe7d4", panel: "#2b3446", accent: "#f1ead8" }
    },
    {
      id: "costume-teddy",
      name: "Teddy",
      category: "skins",
      kind: "costume",
      model: "teddy",
      plainColor: "Honey",
      description: "A birthday teddy costume available on your birthday.",
      priceLabel: "Free",
      priceId: "price_1Tpw0RHmsD7gK0nLmwLsy9E7",
      productId: "prod_UpbCRtUOQpec0E",
      freeClaim: true,
      availability: { type: "birthday", label: "Available on your birthday" },
      colors: { swatch: "#b8793d", torso: "#a86b35", limb: "#7b4b2a", arm: "#c28a52", helmet: "#b8793d", panel: "#f2d0a2", accent: "#ffd166" }
    },
    {
      id: "trail-smoke",
      name: "Smoke Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Smoke",
      description: "A longer smoky boost trail with drifting layered plumes.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHb2HmsD7gK0nLOjctcv4d",
      productId: "prod_UpxWZVT2Mzv5th",
      colors: { swatch: "#8d98a5", accent: "#d8e0ea" }
    },
    {
      id: "trail-water",
      name: "Water Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Water",
      description: "A flowing water boost trail with bubbles and splashes.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHelHmsD7gK0nLiGu02lbg",
      productId: "prod_UpxZyhCmnYPbNd",
      colors: { swatch: "#35c7ff", accent: "#b9f5ff" }
    },
    {
      id: "trail-magic",
      name: "Magic Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Magic",
      description: "A sparkling arcane boost trail with stars and motes.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHfLHmsD7gK0nLyXkhzOhy",
      productId: "prod_UpxaqKDUsfPG8D",
      colors: { swatch: "#a985ff", accent: "#ffe8ff" }
    },
    {
      id: "trail-rainbow",
      name: "Rainbow Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Rainbow",
      description: "A colourful rainbow boost trail with shifting bands.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHgJHmsD7gK0nLI5a6yWzE",
      productId: "prod_UpxbnIZ5SKOnC3",
      colors: { swatch: "#ff73ad", accent: "#ffd84d" }
    },
    {
      id: "trail-plasma",
      name: "Plasma Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Plasma",
      description: "An electric plasma boost trail with neon pulses.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHgnHmsD7gK0nLm6H6j7al",
      productId: "prod_UpxczYYA1xPzXU",
      colors: { swatch: "#64e3ff", accent: "#ff73ff" }
    },
    {
      id: "trail-snow",
      name: "Snow Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Snow",
      description: "A frosty snow boost trail with flakes and mist.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHhJHmsD7gK0nLyi2lR5Sd",
      productId: "prod_UpxcTAhPG1gePO",
      colors: { swatch: "#dffcff", accent: "#ffffff" }
    },
    {
      id: "trail-bats",
      name: "Bat Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Bats",
      description: "A spooky bat boost trail with fluttering silhouettes.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHiCHmsD7gK0nLBIjzEEOB",
      productId: "prod_UpxdJmfhSpp3sU",
      colors: { swatch: "#2b2630", accent: "#a985ff" }
    },
    {
      id: "trail-hearts",
      name: "Heart Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Hearts",
      description: "A sweet heart boost trail with drifting hearts.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHjDHmsD7gK0nLM4NNrgk6",
      productId: "prod_UpxejWrfVwaVr0",
      colors: { swatch: "#ff73ad", accent: "#ffd1e5" }
    },
    {
      id: "trail-flowers",
      name: "Flower Trail",
      category: "skins",
      kind: "trail",
      plainColor: "Flowers",
      description: "A floral boost trail with petals and blossoms.",
      priceLabel: "\u00a37",
      priceId: "price_1TqHjVHmsD7gK0nLrURknwLD",
      productId: "prod_Upxee4KIo3Sksn",
      colors: { swatch: "#66e0b8", accent: "#ffd84d" }
    }
    // build:render:end
  ];
